### PR TITLE
send message with options

### PR DESCRIPTION
**Pull request by snthot**
I couldn't send message to a FIFO queue with the master code, because this type of queue requires MessageGroupId parameter.
I just proposed options... to the sqs_send_message function so it doesn't affect the usage.

Maybe there exist a smarter way to do this. No need to merge this if you have better solutions.
Thanks

### CODE REVIEW

**Comment by tk3369** [comment]
Hi @samoconnor - I'm facing the same issue.  Is this PR going to be merged?  Any issue?

**Comment by mattBrzezinski** [comment]
I’ll take a look at this tomorrow, and get it in for you!

**Comment by tk3369** [comment]
Thanks for take care of this.  We're going to use this package for a production process.

**Comment by mattBrzezinski** [comment]
Slowly working on bringing this package up to current standards. Do you have a timeline @tk3369 for when you are going live with your production stage?

**Comment by tk3369** [comment]
We are probably going live next month. We do have a slightly ugly workaround by calling `sqs` directly.  It’s ok if you need more time to bring it to the next level.

**Comment by mattBrzezinski** [comment]
I can definitely wrap up updating this package and getting this change in there as well in that time frame! I think looking into [AWSCore.jl](https://github.com/JuliaCloud/AWSCore.jl) might also be an option as it's a more mature package.

**Comment by mattBrzezinski** [comment]
Closing in favour of #16 since I did not have permissions to push to this fork.

**Pull request closed without merging**
